library(tm)
library(e1071)
library(MLmetrics)
library(dplyr)
library(jiebaR)
library(jiebaRD)
mixSeg <- worker()
cutter <- worker(bylines = T)
teepr2 <- "https://weilunlo.github.io/KTVcaculator/testKTVcalculator/teepr.csv"
teepr <- read.csv(teepr2, fileEncoding = "BIG5")
